/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdministradorGUI;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Alexs
 */
public class CantidadAsientosPorFila extends javax.swing.JPanel {

    /**
     * Creates new form cAsientosPorFila
     */
    public CantidadAsientosPorFila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        numColumna = new javax.swing.JLabel();
        cAsientosPorColumna = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText(" ");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("   ");
        add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        numColumna.setText("AQUI VA EL NUM COLUMNA");
        jPanel1.add(numColumna);
        jPanel1.add(cAsientosPorColumna);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getcAsientosPorColumna() {
        return cAsientosPorColumna;
    }

    public JLabel getNumColumna() {
        return numColumna;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cAsientosPorColumna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numColumna;
    // End of variables declaration//GEN-END:variables
}
